/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiFlowsRunRouteImport } from './routes/api/flows/run'
import { Route as ApiFlowsRunsRunIdRouteImport } from './routes/api/flows/runs/$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlowsRunRoute = ApiFlowsRunRouteImport.update({
  id: '/api/flows/run',
  path: '/api/flows/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlowsRunsRunIdRoute = ApiFlowsRunsRunIdRouteImport.update({
  id: '/api/flows/runs/$runId',
  path: '/api/flows/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/flows/run': typeof ApiFlowsRunRoute
  '/api/flows/runs/$runId': typeof ApiFlowsRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/flows/run': typeof ApiFlowsRunRoute
  '/api/flows/runs/$runId': typeof ApiFlowsRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/flows/run': typeof ApiFlowsRunRoute
  '/api/flows/runs/$runId': typeof ApiFlowsRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/flows/run' | '/api/flows/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/flows/run' | '/api/flows/runs/$runId'
  id: '__root__' | '/' | '/api/flows/run' | '/api/flows/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiFlowsRunRoute: typeof ApiFlowsRunRoute
  ApiFlowsRunsRunIdRoute: typeof ApiFlowsRunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flows/run': {
      id: '/api/flows/run'
      path: '/api/flows/run'
      fullPath: '/api/flows/run'
      preLoaderRoute: typeof ApiFlowsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flows/runs/$runId': {
      id: '/api/flows/runs/$runId'
      path: '/api/flows/runs/$runId'
      fullPath: '/api/flows/runs/$runId'
      preLoaderRoute: typeof ApiFlowsRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiFlowsRunRoute: ApiFlowsRunRoute,
  ApiFlowsRunsRunIdRoute: ApiFlowsRunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
